spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration

cloud:
  aws:
    region:
      static: ap-south-1
      auto: false
    credentials:
      access-key: XXXX
      secret-key: XXXX
    end-point:
      uri: https://sqs.ap-south-1.amazonaws.com/123456789/spring